### ISSUE TITLE
Error executing

### ISSUE THREAD

**Issue by 0xnim** [pinheadmz/handout#13]

**Comment by 0xnim** [comment]
└─$ sudo node lib/handout.js                                                1 ⨯
/home/nim1com/handout/lib/webserver.js:10
    this.domain = options.domain.slice(0, -1),
                                 ^

TypeError: Cannot read properties of null (reading 'slice')
    at new Webserver (/home/nim1com/handout/lib/webserver.js:10:34)
    at Object.<anonymous> (/home/nim1com/handout/lib/handout.js:23:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by pinheadmz** [comment]
Did you run `hnssec-gen.js`? https://github.com/pinheadmz/handout#2-configure
