### ISSUE TITLE
bns module not find

### ISSUE THREAD

**Issue by Nanashi-B** [pinheadmz/handout#15]
root@raspberrypi:/opt/handout# node scripts/hnssec-gen.js mydomain myip
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'bns'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/handout/scripts/hnssec-gen.js:15:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

i have download bns and bcrypto from their github repo and add it in /opt/handout/script but still have this error

**Comment by pinheadmz** [comment]
did you `npm install` ?

**Comment by pinheadmz** [comment]
https://github.com/pinheadmz/handout#1-install

**Comment by Nanashi-B** [comment]
ah yes okay it was because i didn't have npm installed on my server
