### ISSUE TITLE
node lib/handout.js: this.server.setZSKFromString is not a function

### ISSUE THREAD

**Issue by tuxcanfly** [pinheadmz/handout#4]
```
$> node lib/handout.js
[debug] (webserver) Webserver opened at host 104.131.66.214
TypeError: this.server.setZSKFromString is not a function
    at AuthNS.init (/root/handout/lib/authserver.js:104:17)
        at /root/handout/lib/handout.js:44:10

```

environment: Debian 10, Node v15.11.0

**Comment by pinheadmz** [comment]
Hm, that's weird, handout should be installing my branch of bns:

https://github.com/pinheadmz/handout/blob/6e0aa1f650e2d688a75e4ed5de56bdf511d1ab3f/package.json#L26

which has the `setZSKFromString()` function:

https://github.com/chjj/bns/pull/22/files

**Comment by Frank-Buss** [comment]
I got the same error, when I installed it as a normal user, but then tried to run `lib/handout.js` as root. If I install and run both as root, I get the expected output as described in the readme.

**Comment by Frank-Buss** [comment]
Looks like root was not the problem. I installed it fresh with the latest nodejs version, and got the same error. Installing the bns branch manually after `npm i` fixed it:
```
npm install "https://github.com/pinheadmz/bns#cname1"
```

**Comment by pinheadmz** [comment]
I think old pinned commits in package-lock were causing this, should be fixed in https://github.com/pinheadmz/handout/commit/1f0c3a0ab13c3736d4c890417297e245178e9d6c let me know if that doesnt help
